[package]
name = "g_logger"
version = "0.1.0"
edition = "2018"

[features]
log = ["lazy_static", "serde", "serde_json"] 

[dependencies]
lazy_static = {version="1.4", optional=true}
serde = {version="1.0", optional=true, features=["derive"]}
serde_json = {version="1.0", optional=true}